import { FaEnvelope } from 'react-icons/fa';
import LegalDocumentPage, {
  LegalContactEmail,
  LegalList,
  LegalSection,
  LegalSubSection,
} from '@/components/legal/LegalDocumentPage';

const CONTACT_EMAIL = 'hwseta@hwseta.org.za';
const PORTAL_NAME = 'HWSETA Beneficiary Hub';

export default function PrivacyPage() {
  return (
    <LegalDocumentPage
      breadcrumbTitle="Privacy Policy"
      heading="Privacy Policy"
    >
      <LegalSection title="1. Introduction">
        <p>Welcome to the {PORTAL_NAME}.</p>
        <p>
          The Health and Welfare Sector Education and Training Authority (&quot;HWSETA&quot;, &quot;us&quot;, &quot;we&quot;, or
          &quot;our&quot;) operates this beneficiary portal. Our Privacy Policy governs your visit to the portal and
          explains how we collect, safeguard, and disclose information that results from your use of our services.
        </p>
        <p>
          We use your data to provide and improve the beneficiary portal. By using the portal, you agree to the
          collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy
          Policy, the terms used here have the same meanings as in our Terms and Conditions.
        </p>
      </LegalSection>

      <LegalSection title="2. Definitions">
        <LegalList
          items={[
            <>
              <strong>Service</strong> means the {PORTAL_NAME} website and related beneficiary services operated by
              HWSETA.
            </>,
            <>
              <strong>Personal Data</strong> means data about a living individual who can be identified from those data
              (or from those and other information either in our possession or likely to come into our possession).
            </>,
            <>
              <strong>Usage Data</strong> is data collected automatically, either generated by the use of the Service or
              from the Service infrastructure itself (for example, the duration of a page visit).
            </>,
            <>
              <strong>Cookies</strong> are small files stored on your device (computer or mobile device).
            </>,
            <>
              <strong>Data Controller</strong> means a natural or legal person who determines the purposes for which
              and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy
              Policy, HWSETA is a Data Controller of your data.
            </>,
            <>
              <strong>Data Processors (or Service Providers)</strong> means any natural or legal person who processes
              the data on behalf of the Data Controller.
            </>,
            <>
              <strong>Data Subject</strong> is any living individual who is the subject of Personal Data.
            </>,
            <>
              <strong>The User</strong> is the individual using our Service. The User corresponds to the Data Subject.
            </>,
          ]}
        />
      </LegalSection>

      <LegalSection title="3. Information Collection and Use">
        <p>
          We collect several different types of information for various purposes to provide and improve our Service to
          you.
        </p>
      </LegalSection>

      <LegalSection title="4. Types of Data Collected">
        <LegalSubSection title="4.1 Personal Data">
          <p>
            While using our Service, we may ask you to provide us with certain personally identifiable information that
            can be used to contact or identify you (&quot;Personal Data&quot;). This may include, but is not limited to:
          </p>
          <LegalList
            ordered
            items={[
              'Email address',
              'First name and last name',
              'Phone number',
              'Address, province, postal code, and city',
              'Identity and demographic information required for beneficiary registration',
              'Programme participation and profile information',
              'Cookies and Usage Data',
            ]}
          />
          <p>
            We may use your Personal Data to contact you with service-related notices, programme updates, and other
            information relevant to your beneficiary profile. You may opt out of non-essential communications where
            applicable.
          </p>
        </LegalSubSection>

        <LegalSubSection title="4.2 Usage Data">
          <p>
            We may also collect information that your browser sends whenever you visit our Service or when you access
            the Service through any device (&quot;Usage Data&quot;).
          </p>
        </LegalSubSection>

        <LegalSubSection title="4.3 Location and Device Data">
          <p>
            This Usage Data may include information such as your computer&apos;s Internet Protocol address (IP address),
            browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the
            time spent on those pages, unique device identifiers, and other diagnostic data. When you access the Service
            with a device, this may include the type of device you use, your device unique ID, your device operating
            system, and the type of Internet browser you use.
          </p>
        </LegalSubSection>

        <LegalSubSection title="4.4 Tracking Cookies Data">
          <p>
            We use cookies and similar tracking technologies to track activity on our Service and hold certain
            information. Cookies are files with a small amount of data which may include an anonymous unique identifier.
            You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if
            you do not accept cookies, you may not be able to use some portions of our Service.
          </p>
          <p>Examples of Cookies we use:</p>
          <LegalList
            ordered
            items={[
              <>
                <strong>Session Cookies:</strong> We use Session Cookies to operate our Service.
              </>,
              <>
                <strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various
                settings.
              </>,
              <>
                <strong>Security Cookies:</strong> We use Security Cookies for security purposes.
              </>,
            ]}
          />
        </LegalSubSection>

        <LegalSubSection title="4.5 Other Data">
          <p>
            While using our Service, we may also collect information required for beneficiary monitoring, programme
            enrolment, complaints, surveys, communications, and related administrative processes, including education,
            employment, and contact details where relevant to your profile.
          </p>
        </LegalSubSection>
      </LegalSection>

      <LegalSection title="5. Use of Data">
        <p>HWSETA uses the collected data for various purposes, including to:</p>
        <LegalList
          ordered
          items={[
            'Provide and maintain the beneficiary portal;',
            'Notify you about changes to our Service;',
            'Allow you to participate in interactive features when you choose to do so;',
            'Provide customer and beneficiary support;',
            'Gather analysis or valuable information so that we can improve our Service;',
            'Monitor the usage of our Service;',
            'Detect, prevent, and address technical issues;',
            'Fulfil any other purpose for which you provide it;',
            'Carry out our obligations and enforce our rights arising from any contracts entered into between you and us;',
            'Provide notices about your account, programme participation, and related services;',
            'Support reporting, compliance, and programme administration requirements.',
          ]}
        />
      </LegalSection>

      <LegalSection title="6. Retention of Data">
        <p>
          We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy
          Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations,
          resolve disputes, and enforce our legal agreements and policies.
        </p>
      </LegalSection>

      <LegalSection title="7. Transfer of Data">
        <p>
          Your information, including Personal Data, may be transferred to and maintained on computers located outside
          of your province or country where data protection laws may differ. Your consent to this Privacy Policy
          followed by your submission of such information represents your agreement to that transfer. HWSETA will take
          all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy
          Policy.
        </p>
      </LegalSection>

      <LegalSection title="8. Disclosure of Data">
        <p>We may disclose personal information that we collect, or you provide:</p>
        <LegalSubSection title="8.1 Disclosure for Law Enforcement">
          <p>
            Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or
            in response to valid requests by public authorities.
          </p>
        </LegalSubSection>
        <LegalSubSection title="8.2 Business Transaction">
          <p>
            If we or our subsidiaries are involved in a merger, acquisition, or asset sale, your Personal Data may be
            transferred.
          </p>
        </LegalSubSection>
        <LegalSubSection title="8.3 Other Cases">
          <p>We may disclose your information also:</p>
          <LegalList
            items={[
              'To our subsidiaries and affiliates;',
              'To contractors, service providers, training providers, employers, and other third parties we use to support our business;',
              'To fulfil the purpose for which you provide it;',
              'For any other purpose disclosed by us when you provide the information;',
              'With your consent in any other cases;',
              'If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of HWSETA, our beneficiaries, or others.',
            ]}
          />
        </LegalSubSection>
      </LegalSection>

      <LegalSection title="9. Security of Data">
        <p>
          The security of your data is important to us, but remember that no method of transmission over the Internet or
          method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect
          your Personal Data, we cannot guarantee its absolute security.
        </p>
      </LegalSection>

      <LegalSection title="10. Your Rights">
        <p>You may request access to the personal information we hold about you, including:</p>
        <LegalList
          ordered
          items={[
            'The categories of personal information we have collected about you;',
            'The categories of sources from which we collect your personal information;',
            'The business or commercial purpose for collecting your personal information;',
            'The categories of third parties with whom we share personal information;',
            'The specific pieces of personal information we have collected about you.',
          ]}
        />
        <p>
          You may also request correction or deletion of your personal information, subject to applicable law and
          operational requirements of the beneficiary portal.
        </p>
      </LegalSection>

      <LegalSection title="11. Service Providers">
        <p>
          We may employ third party companies and individuals to facilitate our Service, provide Service on our behalf,
          perform Service-related services, or assist us in analysing how our Service is used. These third parties have
          access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or
          use it for any other purpose.
        </p>
      </LegalSection>

      <LegalSection title="12. Links to Other Sites">
        <p>
          Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you
          will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every
          site you visit. We have no control over and assume no responsibility for the content, privacy policies, or
          practices of any third-party sites or services.
        </p>
      </LegalSection>

      <LegalSection title="13. Children&apos;s Privacy">
        <p>
          Our Services are not intended for use by children under the age of 18 (&quot;Child&quot; or &quot;Children&quot;). We do not
          knowingly collect personally identifiable information from children under 18. If you become aware that a child
          has provided us with Personal Data, please contact us. If we become aware that we have collected Personal
          Data from children without verification of parental consent, we take steps to remove that information from our
          servers.
        </p>
      </LegalSection>

      <LegalSection title="14. Changes to This Privacy Policy">
        <p>
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
          Privacy Policy on this page and updating the effective date at the top of this Privacy Policy. You are advised
          to review this Privacy Policy periodically for any changes.
        </p>
      </LegalSection>

      <LegalSection title="Contact Us">
        <p>If you have any questions about this Privacy Policy, please contact us by email:</p>
        <p className="flex items-center gap-2">
          <FaEnvelope className="h-4 w-4 text-hwseta-green" aria-hidden />
          <LegalContactEmail email={CONTACT_EMAIL} />
        </p>
      </LegalSection>
    </LegalDocumentPage>
  );
}
